/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    MarkdownTest: typeof import('./src/components/MarkdownTest.vue')['default']
    MarkdownValidator: typeof import('./src/components/MarkdownValidator.vue')['default']
    MessageActions: typeof import('./src/components/MessageActions.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Siderbar: typeof import('./src/components/Siderbar.vue')['default']
  }
}
